development:
    app_id: FTZOwPXCe45uTms4k6OZMw
    secret: MYLKkauH7uyBSy6D8HO7CIyNBZ8FPKIblEs3AXYUo
    
test:
    app_id: 12345
    secret: abcdef

production:
    app_id: FTZOwPXCe45uTms4k6OZMw
    secret: MYLKkauH7uyBSy6D8HO7CIyNBZ8FPKIblEs3AXYUo